name = "tetris-game"
main = "src/worker/index.ts"
compatibility_date = "2025-12-13"

routes = [
  { pattern = "tetris.menuhub.me", custom_domain = true }
]

[site]
bucket = "./dist"

[build]
command = "npm run build"


