name = "tetris"
main = "src/worker/index.ts"
compatibility_date = "2024-12-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"

routes = [
  { pattern = "tetris.menuhub.me", custom_domain = true }
]
